os: linux
language: cpp
compiler: gcc
sudo: required
services: docker
before_install:
  - sudo apt-get update
  - sudo apt-get install docker-engine
- docker pull theuni/bitcoin-build-x86_64-pc-linux-gnu
- docker build -t bitcoin-build -f Dockerfile.x86_64-pc-linux-gnu .
script:
- docker run bitcoin-build make check
